# Generated by Django 3.2.18 on 2023-06-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_ratings', models.CharField(max_length=999)),
                ('expected_results', models.CharField(max_length=999)),
                ('points', models.CharField(max_length=999)),
                ('status', models.CharField(max_length=999)),
                ('notes', models.CharField(max_length=999)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
